### ISSUE TITLE
Error downloading dataset

### ISSUE THREAD

**Issue by Krulvis** [ML-course/master#19]
Running this code the process gets interrupted.

```
import openml as oml
import numpy as np
import matplotlib.pyplot as plt
import sklearn

# Download Streetview data. Takes a while the first time.
SVHN = oml.datasets.get_dataset(41081)
X, y, cats, attrs = SVHN.get_data(dataset_format='array',
    target=SVHN.default_target_attribute)
```

`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`
I have 12gig of memory free, can't figure out why I am getting this interrupt.

**Comment by joaquinvanschoren** [comment]
Can you tell me on which line the error occurs?
If it happens on 'get_dataset' - that only downloads the data and stores it on disk. So then the error could either be that your connection hung up (too slow, network reset,...) or it could be a disk space issue or a permissions issue. OpenML tries to cache the dataset in your home directory (in a folder called '.openml'). You need to have about 3Gb available to store both the original dataset and the python images. It could also be a permissions issue if the process is not allowed to write in your home directory.
If it happens on the second line (get_data) then it is more likely to be memory related - maybe your python process does not get enough of your memory.

If you run your notebook from the command line, also check the command line output for any error messages from the OS or Jupyter.

**Comment by joaquinvanschoren** [comment]
We're looking into using arrow for caching instead of pickle. It is more reliable for large files and loads a lot faster.
